name: "Send Preview Link"

on: issue_comment

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: netlify[bot]
      - run: |
          echo "${{ steps.fc.outputs.comment-body }}"
      - name: Add comment
        uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello and thank you for your contribution! A moderator will check the links on your page within the next 48 hours. © [Tai Studio](https://tai-studio.netlify.app/) 2021/2022