name: "Create Page"

on: issues

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Create Page
        run: |
          npm run creator -- --body="${{ github.event.issue.body }}"
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "Lyna[bot]"
          git commit -m "➕ Create New Page" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
  add-comment:
      if: github.event.label.name == 'Request Page'
      runs-on: ubuntu-latest
      permissions:
        issues: write
      steps:
        - name: Add comment
          uses: peter-evans/create-or-update-comment@c9fcb64660bc90ec1cc535646af190c992007c32
          with:
            issue-number: ${{ github.event.issue.number }}
            body: |
              This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles: